# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python bing.py
    - name: GitHub Push
      # You may pin to the exact commit or the version.
      # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: $\{{ secrets.GITHUB_TOKEN }}
        repository: ${GITHUB_REPOSITORY}
        branch:  master

